const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-white px-6 py-16 md:py-24">
      <div className="max-w-3xl mx-auto" style={{ fontFamily: "'DM Sans', sans-serif", color: "hsl(0 0% 15%)" }}>
        <p className="text-xs uppercase tracking-[0.2em] mb-2" style={{ color: "hsl(0 0% 50%)" }}>
          ALEXANDRIA | Privacy Policy
        </p>
        <h1 className="text-4xl md:text-5xl font-bold mb-2" style={{ fontFamily: "'DM Serif Display', serif" }}>
          PRIVACY POLICY
        </h1>
        <p className="text-lg mb-1" style={{ color: "hsl(210 50% 40%)" }}>
          Alexandria B2B Terminal for Pharma Intelligence
        </p>
        <p className="text-sm mb-12" style={{ color: "hsl(0 0% 50%)" }}>
          Effective Date: 2 April 2026 &nbsp;|&nbsp; Last Updated: 2 April 2026
        </p>

        <hr className="border-t-2 border-[hsl(210,50%,35%)] mb-10" />

        <Section title="1. Introduction">
          <p>
            This Privacy Policy ("Policy") describes how Alexandria ("we," "us," or "our") collects, uses,
            discloses, and protects information obtained through the Alexandria B2B Terminal for Pharma
            Intelligence ("Platform"), a business-to-business AI research discovery system designed for
            pharmaceutical and life sciences organisations ("Clients").
          </p>
          <p className="mt-4">
            This Policy applies to all authorised users ("Users") accessing the Platform under a Client's
            enterprise subscription agreement. By accessing or using the Platform, you acknowledge that
            you have read, understood, and agree to the practices described herein.
          </p>
        </Section>

        <Section title="2. Definitions">
          <Definition term="Client Data" text="Proprietary datasets, research queries, pipeline intelligence, compound libraries, and other business information uploaded or processed through the Platform by or on behalf of a Client." />
          <Definition term="Usage Data" text="Technical and behavioural data generated through interaction with the Platform, including query logs, feature utilisation metrics, session metadata, and system performance telemetry." />
          <Definition term="Personal Data" text="Information that identifies or can reasonably be linked to an individual User, such as name, email address, job title, and authentication credentials." />
          <Definition term="Derived Insights" text="Aggregated, de-identified analytical outputs generated by the Platform's AI models that cannot be attributed to any single Client or User." />
        </Section>

        <Section title="3. Information We Collect">
          <SubSection title="3.1 Information Provided by Clients and Users">
            <table className="w-full text-sm border border-gray-200 mb-6">
              <thead>
                <tr className="bg-[hsl(210,50%,25%)] text-white">
                  <th className="text-left px-4 py-2 font-semibold">Category</th>
                  <th className="text-left px-4 py-2 font-semibold">Details</th>
                </tr>
              </thead>
              <tbody>
                <TableRow c1="Account Information" c2="Organisation name, billing contact, enterprise domain, and subscription tier provisioned by Client administrator." />
                <TableRow c1="User Credentials" c2="Full name, corporate email address, job title/role, and SSO/SAML authentication tokens." />
                <TableRow c1="Research Queries" c2="Search terms, natural language prompts, filters, and parameters submitted to Alexandria's AI discovery engine." />
                <TableRow c1="Uploaded Content" c2="Documents, datasets, compound structures, clinical trial protocols, and other files uploaded for analysis." />
                <TableRow c1="Feedback & Annotations" c2="Relevance ratings, saved searches, bookmarks, notes, and collaborative workspace contributions." />
              </tbody>
            </table>
          </SubSection>

          <SubSection title="3.2 Information Collected Automatically">
            <ul className="list-disc pl-6 space-y-1">
              <li>IP address, device type, operating system, and browser/terminal client version</li>
              <li>Session duration, feature utilisation patterns, and navigation paths</li>
              <li>API call logs, query response times, and error reports</li>
              <li>Authentication events and access control audit trails</li>
            </ul>
          </SubSection>

          <SubSection title="3.3 Information from Third-Party Sources">
            <p>
              We may enrich Platform functionality by integrating data from licensed third-party
              pharmaceutical databases, public biomedical repositories (e.g., PubMed, ClinicalTrials.gov,
              patent registries), and Client-authorised data connectors. We do not purchase personal data
              from third-party brokers.
            </p>
          </SubSection>
        </Section>

        <Section title="4. How We Use Information">
          <SubSection title="4.1 Platform Operations">
            <ul className="list-disc pl-6 space-y-1">
              <li>Delivering AI-powered research discovery, literature analysis, and competitive intelligence outputs</li>
              <li>Processing and responding to natural language queries against pharmaceutical knowledge graphs</li>
              <li>Maintaining User accounts, enforcing role-based access controls, and managing authentication</li>
              <li>Providing technical support and resolving service incidents</li>
            </ul>
          </SubSection>

          <SubSection title="4.2 Platform Improvement">
            <ul className="list-disc pl-6 space-y-1">
              <li>Training and refining AI models using Derived Insights only (never raw Client Data)</li>
              <li>Analysing aggregated Usage Data to optimise search relevance, latency, and feature design</li>
              <li>Conducting internal research and development on information retrieval methodologies</li>
            </ul>
          </SubSection>

          <SubSection title="4.3 Security and Compliance">
            <ul className="list-disc pl-6 space-y-1">
              <li>Detecting, investigating, and preventing fraudulent, unauthorised, or malicious activity</li>
              <li>Maintaining audit logs for regulatory compliance (e.g., GxP, SOX, HIPAA where applicable)</li>
              <li>Enforcing the Terms of Service and enterprise subscription agreements</li>
            </ul>
          </SubSection>

          <SubSection title="4.4 Communications">
            <ul className="list-disc pl-6 space-y-1">
              <li>Sending service-critical notifications (outages, security alerts, policy updates)</li>
              <li>Providing Client administrators with usage analytics and adoption reports</li>
            </ul>
          </SubSection>
        </Section>

        <Section title="5. Legal Bases for Processing (GDPR / UK GDPR)">
          <p className="mb-4">
            Where EU or UK data protection law applies, we process Personal Data under the following legal bases:
          </p>
          <table className="w-full text-sm border border-gray-200 mb-6">
            <thead>
              <tr className="bg-[hsl(210,50%,25%)] text-white">
                <th className="text-left px-4 py-2 font-semibold">Legal Basis</th>
                <th className="text-left px-4 py-2 font-semibold">Application</th>
              </tr>
            </thead>
            <tbody>
              <TableRow c1="Contract Performance" c2="Processing necessary to deliver the Platform under the Client's subscription agreement." />
              <TableRow c1="Legitimate Interests" c2="Platform security, fraud prevention, service improvement using aggregated/de-identified data." />
              <TableRow c1="Legal Obligation" c2="Compliance with applicable laws, regulations, or enforceable governmental requests." />
              <TableRow c1="Consent" c2="Where explicitly obtained for optional processing activities (e.g., marketing communications)." />
            </tbody>
          </table>
        </Section>

        <Section title="6. Data Sharing and Disclosure">
          <p className="mb-4">
            We do not sell, rent, or trade Client Data or Personal Data. We may share information only in
            the following circumstances:
          </p>

          <SubSection title="6.1 Within the Client Organisation">
            <p>
              Client administrators may access usage analytics and user activity within their organisation's
              tenant, consistent with their enterprise agreement.
            </p>
          </SubSection>

          <SubSection title="6.2 Service Providers">
            <p>
              We engage vetted sub-processors to provide cloud infrastructure, authentication services,
              monitoring, and support tooling. All sub-processors are bound by data processing agreements
              with equivalent or stronger protections than this Policy. A current list of sub-processors is
              available upon request.
            </p>
          </SubSection>

          <SubSection title="6.3 Legal and Regulatory Compliance">
            <p>
              We may disclose information when required by law, subpoena, court order, or governmental
              regulation, or when we believe disclosure is necessary to protect our rights, the safety of Users,
              or the public interest.
            </p>
          </SubSection>

          <SubSection title="6.4 Business Transfers">
            <p>
              In the event of a merger, acquisition, reorganisation, or sale of assets, information may be
              transferred as part of the transaction. Clients will be notified in advance and may terminate their
              agreement if they object.
            </p>
          </SubSection>
        </Section>

        <Section title="7. Data Security">
          <p className="mb-4">
            We implement industry-standard technical and organisational measures to protect information
            against unauthorised access, alteration, disclosure, or destruction:
          </p>
          <ul className="list-disc pl-6 space-y-1 mb-4">
            <li>Encryption at rest (AES-256) and in transit (TLS 1.3)</li>
            <li>Tenant-level data isolation with cryptographic key separation</li>
            <li>Role-based access control (RBAC) with principle of least privilege</li>
            <li>SSO/SAML 2.0 integration with enforced multi-factor authentication</li>
            <li>Continuous vulnerability scanning, annual penetration testing, and SOC 2 Type II certification</li>
            <li>Immutable audit logging with tamper-evident controls</li>
            <li>Automated data loss prevention (DLP) policies on egress</li>
          </ul>
          <p>
            No system is completely secure. We commit to promptly notifying affected Clients of any
            confirmed data breach in accordance with applicable law and contractual obligations.
          </p>
        </Section>

        <Section title="8. Data Retention">
          <p className="mb-4">
            We retain information only for as long as necessary to fulfil the purposes described in this Policy:
          </p>
          <table className="w-full text-sm border border-gray-200 mb-6">
            <thead>
              <tr className="bg-[hsl(210,50%,25%)] text-white">
                <th className="text-left px-4 py-2 font-semibold">Data Type</th>
                <th className="text-left px-4 py-2 font-semibold">Retention Period</th>
                <th className="text-left px-4 py-2 font-semibold">Basis</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-200">
                <td className="px-4 py-2">Client Data</td>
                <td className="px-4 py-2">Duration of subscription + 90 days</td>
                <td className="px-4 py-2">Contract performance; Client deletion requests honoured within 30 days.</td>
              </tr>
              <tr className="border-b border-gray-200">
                <td className="px-4 py-2">User Credentials</td>
                <td className="px-4 py-2">Duration of active account + 90 days</td>
                <td className="px-4 py-2">Deleted upon account deactivation by Client admin.</td>
              </tr>
              <tr className="border-b border-gray-200">
                <td className="px-4 py-2">Usage Data</td>
                <td className="px-4 py-2">24 months from collection</td>
                <td className="px-4 py-2">Aggregated and de-identified after retention period.</td>
              </tr>
              <tr className="border-b border-gray-200">
                <td className="px-4 py-2">Audit Logs</td>
                <td className="px-4 py-2">7 years</td>
                <td className="px-4 py-2">Regulatory compliance (GxP, SOX).</td>
              </tr>
              <tr className="border-b border-gray-200">
                <td className="px-4 py-2">Derived Insights</td>
                <td className="px-4 py-2">Indefinite (fully de-identified)</td>
                <td className="px-4 py-2">Cannot be attributed to any Client or User.</td>
              </tr>
            </tbody>
          </table>
          <p>
            Upon contract termination, Clients may request export of their Client Data in machine-readable
            format within the 90-day post-termination window. After this period, Client Data is permanently
            deleted using cryptographic erasure.
          </p>
        </Section>

        <Section title="9. International Data Transfers">
          <p className="mb-4">
            The Platform may process data in jurisdictions outside your country of residence. Where
            Personal Data is transferred from the EEA, UK, or Switzerland to jurisdictions not deemed
            adequate by the European Commission or UK Secretary of State, we rely on:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Standard Contractual Clauses (SCCs) approved by the European Commission</li>
            <li>UK International Data Transfer Agreement or Addendum, as applicable</li>
            <li>Supplementary technical measures (encryption, pseudonymisation, access controls) assessed via Transfer Impact Assessments</li>
          </ul>
        </Section>

        <Section title="10. Individual Rights">
          <p className="mb-4">
            Depending on your jurisdiction, you may exercise the following rights by contacting your Client
            administrator or our Data Protection team:
          </p>
          <ul className="list-disc pl-6 space-y-1 mb-4">
            <li>Access: Request a copy of the Personal Data we hold about you.</li>
            <li>Rectification: Request correction of inaccurate or incomplete Personal Data.</li>
            <li>Erasure: Request deletion of your Personal Data, subject to legal retention obligations.</li>
            <li>Restriction: Request limitation of processing in specific circumstances.</li>
            <li>Portability: Receive your Personal Data in a structured, machine-readable format.</li>
            <li>Objection: Object to processing based on legitimate interests.</li>
            <li>Withdraw Consent: Where processing is based on consent, withdraw it at any time without affecting prior lawful processing.</li>
          </ul>
          <p>
            We respond to verified requests within 30 days (or as required by applicable law). For B2B
            Users, certain requests may need to be routed through your Client's administrator per the
            enterprise agreement.
          </p>
        </Section>

        <Section title="11. AI-Specific Provisions">
          <SubSection title="11.1 Model Training">
            <p>
              Alexandria's AI models are trained on publicly available biomedical literature, licensed datasets,
              and Derived Insights. Raw Client Data is never used for model training unless a Client provides
              explicit, documented, opt-in consent under a separate agreement.
            </p>
          </SubSection>

          <SubSection title="11.2 Automated Decision-Making">
            <p>
              The Platform provides AI-generated research outputs, rankings, and recommendations as
              decision-support tools. It does not make automated decisions with legal or similarly significant
              effects on individuals. All outputs are subject to human review and professional judgement.
            </p>
          </SubSection>

          <SubSection title="11.3 Prompt and Query Logging">
            <p>
              User queries are logged for service delivery, debugging, and abuse prevention. Logs are
              retained per the Usage Data retention schedule and are not shared outside the Client's tenant.
            </p>
          </SubSection>
        </Section>

        <Section title="12. Cookies and Tracking Technologies">
          <p>
            The Platform uses strictly necessary cookies and session tokens for authentication, security,
            and session management. We do not use advertising cookies, cross-site tracking pixels, or
            third-party behavioural analytics within the Platform. If the Platform includes any optional
            analytics, Clients may configure these through the administration console.
          </p>
        </Section>

        <Section title="13. Children's Privacy">
          <p>
            The Platform is a B2B enterprise product and is not directed at individuals under the age of 18.
            We do not knowingly collect Personal Data from minors. If we become aware that we have
            inadvertently collected such data, we will delete it promptly.
          </p>
        </Section>

        <Section title="14. Changes to This Policy">
          <p>
            We may update this Policy to reflect changes in our practices, technology, legal requirements,
            or regulatory guidance. Material changes will be communicated to Client administrators at least
            30 days before taking effect via email notification and in-platform banner. Continued use of the
            Platform after the effective date constitutes acceptance of the updated Policy.
          </p>
        </Section>

        <Section title="15. Contact Information">
          <p className="mb-4">For questions, concerns, or to exercise your data protection rights:</p>
          <div className="mb-4">
            <p className="font-bold">Data Protection Officer</p>
            <p>Alexandria Limited</p>
            <p>Email: <a href="mailto:privacy@alexandrialabs.uk" className="underline" style={{ color: "hsl(210 50% 40%)" }}>privacy@alexandrialabs.uk</a></p>
            <p>Web: <a href="https://alexandrialabs.uk/privacy" className="underline" style={{ color: "hsl(210 50% 40%)" }}>https://alexandrialabs.uk/privacy</a></p>
          </div>
          <p>
            If you are located in the EEA or UK and believe your data protection rights have not been
            adequately addressed, you have the right to lodge a complaint with your local supervisory
            authority.
          </p>
        </Section>
      </div>
    </div>
  );
};

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-10">
    <hr className="border-t-2 border-[hsl(210,50%,35%)] mb-8" />
    <h2 className="text-2xl md:text-3xl font-bold mb-4" style={{ fontFamily: "'DM Serif Display', serif", color: "hsl(210 50% 25%)" }}>
      {title}
    </h2>
    {children}
  </div>
);

const SubSection = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-6">
    <h3 className="text-lg font-semibold mb-2" style={{ color: "hsl(210 50% 35%)" }}>
      {title}
    </h3>
    {children}
  </div>
);

const Definition = ({ term, text }: { term: string; text: string }) => (
  <p className="mb-3">
    <strong>{term}:</strong> {text}
  </p>
);

const TableRow = ({ c1, c2 }: { c1: string; c2: string }) => (
  <tr className="border-b border-gray-200">
    <td className="px-4 py-2">{c1}</td>
    <td className="px-4 py-2">{c2}</td>
  </tr>
);

export default PrivacyPolicy;
