import Footer from "@/components/Footer";

const Terms = () => {
  return (
    <div className="min-h-screen" style={{ background: "hsl(0 0% 3%)" }}>
      <div className="max-w-3xl mx-auto px-6 py-20 md:py-32">
        <a
          href="/"
          className="inline-flex items-center gap-1.5 text-xs font-medium mb-8 transition-colors"
          style={{ color: "hsl(0 0% 50%)" }}
          onMouseEnter={(e) => (e.currentTarget.style.color = "hsl(0 0% 80%)")}
          onMouseLeave={(e) => (e.currentTarget.style.color = "hsl(0 0% 50%)")}
        >
          &larr; Back to Home
        </a>
        <p className="text-mono text-xs uppercase tracking-[0.2em] mb-4 text-muted-foreground">
          Terms &amp; Conditions
        </p>
        <h1 className="text-display text-4xl md:text-6xl tracking-tight mb-3" style={{ color: "hsl(0 0% 92%)" }}>
          Terms &amp; Conditions
        </h1>
        <p className="text-sm mb-8" style={{ color: "hsl(0 0% 40%)" }}>
          Effective Date: 2 April 2026 &nbsp;|&nbsp; Version 1.0
        </p>

        {/* Acceptance Notice */}
        <div className="rounded-lg px-5 py-4 mb-10" style={{ background: "hsl(36 60% 20% / 0.2)", border: "1px solid hsl(36 60% 30% / 0.3)" }}>
          <p className="text-xs leading-relaxed" style={{ color: "hsl(36 60% 65%)" }}>
            <span className="font-semibold">Important:</span> By accessing or using the Alexandria Platform, you agree to be bound by these Terms &amp; Conditions. If you do not agree, do not access or use the Platform. If you are accepting on behalf of an organisation, you represent that you have authority to bind that organisation.
          </p>
        </div>

        <Section title="1. Agreement Overview">
          <p>
            These Terms and Conditions (&ldquo;Agreement&rdquo;) constitute a legally binding contract between the entity subscribing to the service (&ldquo;Client,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and Alexandria (&ldquo;Provider,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) governing access to and use of the Alexandria B2B Terminal for Pharma Intelligence (&ldquo;Platform&rdquo;).
          </p>
          <p className="mt-3 italic" style={{ color: "hsl(0 0% 45%)" }}>
            This Agreement incorporates by reference: (i) the applicable Order Form or Statement of Work; (ii) the Data Processing Agreement; (iii) the Service Level Agreement; (iv) the Acceptable Use Policy; and (v) the Privacy Policy.
          </p>
        </Section>

        <Section title="2. Definitions">
          <table className="w-full text-sm mb-6 border-collapse">
            <thead>
              <tr style={{ background: "hsl(var(--primary))" }}>
                <th className="text-left px-4 py-3 font-medium text-white">Term</th>
                <th className="text-left px-4 py-3 font-medium text-white">Definition</th>
              </tr>
            </thead>
            <tbody>
              <DefRow term="Authorised User" def="An individual employee, contractor, or agent of the Client who has been granted access credentials by the Client's administrator." />
              <DefRow term="Client Data" def="All data, content, research queries, compound libraries, pipeline intelligence, and other information uploaded to, submitted through, or generated within the Platform by or on behalf of the Client." />
              <DefRow term="Confidential Information" def="Any non-public information disclosed by either party that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information." />
              <DefRow term="Derived Insights" def="Aggregated, de-identified analytical outputs generated by the Platform's AI models that cannot be attributed to any single Client or User." />
              <DefRow term="Documentation" def="User guides, API references, integration specifications, and other technical materials describing the Platform's functionality." />
              <DefRow term="Order Form" def="The mutually executed document specifying subscription tier, Authorised User count, fees, term, and any additional terms." />
              <DefRow term="Subscription Term" def="The period during which the Client is authorised to access the Platform, as specified in the Order Form." />
            </tbody>
          </table>
        </Section>

        <Section title="3. Grant of Rights">
          <SubSection title="3.1 Licence Grant">
            <p>
              Subject to the Client&rsquo;s compliance with this Agreement and timely payment of all applicable fees, the Provider grants to the Client a non-exclusive, non-transferable, non-sublicensable, revocable licence during the Subscription Term to:
            </p>
            <ol className="list-decimal pl-6 space-y-1 mt-2">
              <li>Access and use the Platform for internal business purposes in pharmaceutical and life sciences research, competitive intelligence, and drug discovery support.</li>
              <li>Permit the number of Authorised Users specified in the Order Form to access the Platform using assigned credentials.</li>
              <li>Integrate the Platform with internal systems via documented APIs, subject to the usage limits specified in the Order Form.</li>
            </ol>
          </SubSection>
          <SubSection title="3.2 Restrictions">
            <p>The Client shall not, and shall ensure that its Authorised Users do not:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Sublicence, resell, distribute, or make the Platform available to any third party, including affiliates not covered by the Order Form.</li>
              <li>Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code, algorithms, or model weights of the Platform.</li>
              <li>Use the Platform to build a competing product or service, or to benchmark the Platform for competitive purposes without prior written consent.</li>
              <li>Remove, alter, or obscure any proprietary notices, labels, or marks on the Platform or its outputs.</li>
              <li>Circumvent or disable any security, access control, rate-limiting, or usage-monitoring features.</li>
              <li>Use the Platform in any manner that violates applicable law, including data protection, anti-bribery, export control, and pharmaceutical regulations.</li>
              <li>Submit queries or data designed to extract training data, probe model boundaries for adversarial exploitation, or inject prompts intended to override system instructions.</li>
            </ul>
          </SubSection>
        </Section>

        <Section title="4. Client Data & Intellectual Property">
          <SubSection title="4.1 Ownership of Client Data">
            <p>The Client retains all right, title, and interest in and to Client Data. Nothing in this Agreement transfers ownership of Client Data to the Provider. The Client grants the Provider a limited, non-exclusive licence to process Client Data solely as necessary to deliver the Platform.</p>
          </SubSection>
          <SubSection title="4.2 Ownership of the Platform">
            <p>The Provider retains all right, title, and interest in and to the Platform, including all AI models, algorithms, software, interfaces, documentation, and Derived Insights. No rights to the Provider&rsquo;s intellectual property are granted except as set forth in Section 3.1.</p>
          </SubSection>
          <SubSection title="4.3 Derived Insights">
            <p>The Provider may generate aggregated, de-identified, and anonymised analytical outputs (&ldquo;Derived Insights&rdquo;) from use of the Platform. Derived Insights shall not identify the Client or any Authorised User. The Provider owns all Derived Insights and may use them for service improvement, benchmarking, research, and product development.</p>
          </SubSection>
          <SubSection title="4.4 Feedback">
            <p>If the Client provides suggestions, enhancement requests, or other feedback regarding the Platform, the Provider may use such feedback without restriction or obligation. The Client hereby assigns to the Provider all intellectual property rights arising from such feedback.</p>
          </SubSection>
        </Section>

        <Section title="5. AI-Specific Terms">
          <SubSection title="5.1 Nature of AI Outputs">
            <p>The Platform generates outputs using artificial intelligence models trained on biomedical literature, licensed databases, and Derived Insights. AI-generated outputs are provided as research support tools and do not constitute professional advice, regulatory submissions, or validated scientific conclusions. The Client is solely responsible for evaluating and acting upon any AI-generated output.</p>
          </SubSection>
          <SubSection title="5.2 No Use for Clinical Decision-Making">
            <p>The Platform is not a medical device, clinical decision support system, or diagnostic tool. The Client shall not use AI outputs as the sole basis for clinical trial design, patient treatment decisions, regulatory filings, or safety assessments without independent verification by qualified professionals.</p>
          </SubSection>
          <SubSection title="5.3 Model Training">
            <p>The Provider will not use raw Client Data to train, fine-tune, or improve AI models unless the Client provides explicit, documented, opt-in consent under a separate data licensing agreement. Derived Insights (fully de-identified) may be used for model improvement.</p>
          </SubSection>
          <SubSection title="5.4 Model Updates">
            <p>The Provider may update, retrain, or replace AI models used within the Platform. The Provider will use commercially reasonable efforts to maintain or improve output quality and will notify Clients of material changes to model behaviour through release notes or the administration console.</p>
          </SubSection>
          <SubSection title="5.5 AI Hallucination Disclaimer">
            <p>AI models may generate outputs that are inaccurate, incomplete, or fabricated (&ldquo;hallucinations&rdquo;). The Provider implements quality controls and retrieval-augmented generation techniques to mitigate this risk, but does not guarantee the accuracy of any individual output. The Client acknowledges this inherent limitation.</p>
          </SubSection>
        </Section>

        <Section title="6. Fees & Payment">
          <SubSection title="6.1 Subscription Fees">
            <p>The Client shall pay the subscription fees specified in the Order Form. Unless otherwise stated, fees are quoted in GBP, invoiced annually in advance, and due within 30 days of invoice date.</p>
          </SubSection>
          <SubSection title="6.2 Overages">
            <p>If the Client exceeds usage limits specified in the Order Form (e.g., API call volume, Authorised User count, or storage allocation), the Provider will notify the Client and invoice overage charges at the rates specified in the Order Form. The Provider reserves the right to throttle or suspend access if overages remain unresolved for more than 15 business days.</p>
          </SubSection>
          <SubSection title="6.3 Taxes">
            <p>All fees are exclusive of VAT, sales tax, withholding tax, and other applicable taxes. The Client is responsible for all such taxes, except for taxes on the Provider&rsquo;s net income.</p>
          </SubSection>
          <SubSection title="6.4 Late Payment">
            <p>Overdue amounts accrue interest at the rate of 2% per month (or the maximum rate permitted by law, if lower), calculated from the due date until payment is received in full. The Provider may suspend access if any invoice remains unpaid for more than 45 days past its due date.</p>
          </SubSection>
          <SubSection title="6.5 Fee Adjustments">
            <p>The Provider may adjust fees upon renewal by providing at least 60 days&rsquo; written notice prior to the start of a renewal Subscription Term. If the Client does not accept the adjusted fees, the Client may terminate by providing written notice before the renewal date.</p>
          </SubSection>
        </Section>

        <Section title="7. Term & Termination">
          <SubSection title="7.1 Subscription Term">
            <p>The initial Subscription Term is specified in the Order Form. Unless either party provides written notice of non-renewal at least 60 days before the end of the then-current term, the Agreement will automatically renew for successive periods equal in length to the initial Subscription Term.</p>
          </SubSection>
          <SubSection title="7.2 Termination for Cause">
            <p>Either party may terminate this Agreement immediately upon written notice if the other party:</p>
            <ol className="list-decimal pl-6 space-y-1 mt-2">
              <li>Commits a material breach and fails to cure such breach within 30 days of receiving written notice.</li>
              <li>Becomes insolvent, files for bankruptcy, enters administration or receivership, or ceases to operate in the ordinary course of business.</li>
              <li>Is subject to a change of control resulting in a direct competitor of the non-terminating party acquiring control.</li>
            </ol>
          </SubSection>
          <SubSection title="7.3 Termination for Convenience">
            <p>The Client may terminate this Agreement for convenience upon 90 days&rsquo; prior written notice, provided that no refund of prepaid fees shall be due for the remainder of the then-current Subscription Term.</p>
          </SubSection>
          <SubSection title="7.4 Effects of Termination">
            <p>Upon termination or expiration:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>The Client&rsquo;s and all Authorised Users&rsquo; access to the Platform will be deactivated.</li>
              <li>The Client may request export of Client Data in a machine-readable format within 90 days. After this period, Client Data will be permanently deleted using cryptographic erasure.</li>
              <li>All outstanding fees become immediately due and payable.</li>
              <li>Each party shall return or destroy all Confidential Information of the other party, except as required by law.</li>
              <li>Sections that by their nature should survive termination (including Sections 4, 8, 9, 10, 11, 12, 14, and 15) shall survive.</li>
            </ul>
          </SubSection>
        </Section>

        <Section title="8. Confidentiality">
          <SubSection title="8.1 Obligations">
            <p>Each party (&ldquo;Receiving Party&rdquo;) shall: (a) hold the Confidential Information of the other party (&ldquo;Disclosing Party&rdquo;) in strict confidence; (b) not disclose it to any third party except as permitted herein; and (c) use it solely for the purposes contemplated by this Agreement.</p>
          </SubSection>
          <SubSection title="8.2 Permitted Disclosures">
            <p>The Receiving Party may disclose Confidential Information to employees, contractors, and professional advisors with a need to know who are bound by equivalent confidentiality obligations. Disclosure is also permitted to the extent required by law, regulation, or court order, provided the Disclosing Party receives prompt notice (where legally permitted) to seek a protective order.</p>
          </SubSection>
          <SubSection title="8.3 Exclusions">
            <p>Confidential Information does not include information that: (a) is or becomes publicly available through no fault of the Receiving Party; (b) was rightfully known prior to disclosure; (c) is independently developed without use of the Disclosing Party&rsquo;s Confidential Information; or (d) is rightfully obtained from a third party without restriction.</p>
          </SubSection>
        </Section>

        <Section title="9. Data Protection">
          <p>The parties&rsquo; respective obligations regarding the processing of personal data are set forth in the Data Processing Agreement (&ldquo;DPA&rdquo;), which is incorporated by reference. In the event of a conflict between this Agreement and the DPA, the DPA shall prevail with respect to data protection matters.</p>
          <p className="mt-3">The Provider acts as a data processor (or sub-processor, as applicable) on behalf of the Client. The Provider will process personal data only in accordance with the Client&rsquo;s documented instructions and applicable data protection laws, including the UK GDPR, EU GDPR, and other relevant regulations.</p>
        </Section>

        <Section title="10. Warranties & Disclaimers">
          <SubSection title="10.1 Provider Warranties">
            <p>The Provider warrants that:</p>
            <ol className="list-decimal pl-6 space-y-1 mt-2">
              <li>The Platform will perform materially in accordance with the Documentation during the Subscription Term.</li>
              <li>The Provider will deliver the Platform using commercially reasonable skill and care.</li>
              <li>The Provider has the right and authority to grant the licences set forth in this Agreement.</li>
              <li>The Provider will comply with all applicable laws in the performance of its obligations.</li>
            </ol>
          </SubSection>
          <SubSection title="10.2 Client Warranties">
            <p>The Client warrants that:</p>
            <ol className="list-decimal pl-6 space-y-1 mt-2">
              <li>It has the right and authority to enter into this Agreement and to submit Client Data to the Platform.</li>
              <li>Client Data will not infringe the intellectual property rights of any third party.</li>
              <li>The Client will use the Platform in compliance with all applicable laws, regulations, and industry codes of conduct.</li>
            </ol>
          </SubSection>
          <SubSection title="10.3 Disclaimer">
            <div className="rounded-lg px-4 py-3 mt-2 text-[11px] font-semibold leading-relaxed" style={{ background: "hsl(0 0% 8%)", border: "1px solid hsl(0 0% 15%)", color: "hsl(0 0% 55%)" }}>
              EXCEPT AS EXPRESSLY SET FORTH IN THIS SECTION 10, THE PLATFORM IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE.&rdquo; THE PROVIDER DISCLAIMS ALL OTHER WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, TITLE, AND NON-INFRINGEMENT. THE PROVIDER DOES NOT WARRANT THAT AI-GENERATED OUTPUTS WILL BE ACCURATE, COMPLETE, OR FREE OF ERRORS.
            </div>
          </SubSection>
        </Section>

        <Section title="11. Limitation of Liability">
          <SubSection title="11.1 Cap on Liability">
            <div className="rounded-lg px-4 py-3 text-[11px] font-semibold leading-relaxed" style={{ background: "hsl(0 0% 8%)", border: "1px solid hsl(0 0% 15%)", color: "hsl(0 0% 55%)" }}>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EACH PARTY&rsquo;S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT SHALL NOT EXCEED THE TOTAL FEES PAID OR PAYABLE BY THE CLIENT IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
            </div>
          </SubSection>
          <SubSection title="11.2 Exclusion of Consequential Damages">
            <div className="rounded-lg px-4 py-3 text-[11px] font-semibold leading-relaxed" style={{ background: "hsl(0 0% 8%)", border: "1px solid hsl(0 0% 15%)", color: "hsl(0 0% 55%)" }}>
              NEITHER PARTY SHALL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, REVENUE, DATA, BUSINESS OPPORTUNITIES, GOODWILL, OR ANTICIPATED SAVINGS, REGARDLESS OF THE CAUSE OF ACTION OR THE THEORY OF LIABILITY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </div>
          </SubSection>
          <SubSection title="11.3 Exceptions">
            <p>The limitations in Sections 11.1 and 11.2 shall not apply to: (a) a party&rsquo;s breach of Section 8 (Confidentiality); (b) indemnification obligations under Section 12; (c) the Client&rsquo;s payment obligations; (d) liability arising from wilful misconduct or fraud; or (e) liability that cannot be excluded or limited under applicable law.</p>
          </SubSection>
        </Section>

        <Section title="12. Indemnification">
          <SubSection title="12.1 Provider Indemnity">
            <p>The Provider shall defend, indemnify, and hold harmless the Client from third-party claims that the Platform infringes the intellectual property rights of a third party. This obligation does not apply if the alleged infringement arises from: (a) use in combination with unapproved third-party products; (b) modification by anyone other than the Provider; (c) Client Data; or (d) continued use after a cease-use notice.</p>
          </SubSection>
          <SubSection title="12.2 Client Indemnity">
            <p>The Client shall defend, indemnify, and hold harmless the Provider from third-party claims arising from: (a) Client Data; (b) the Client&rsquo;s violation of applicable laws; or (c) breach of the restrictions in Section 3.2.</p>
          </SubSection>
          <SubSection title="12.3 Procedure">
            <p>The indemnified party shall: (a) provide prompt written notice of the claim; (b) grant the indemnifying party sole control over the defence and settlement; and (c) provide reasonable cooperation.</p>
          </SubSection>
        </Section>

        <Section title="13. Service Levels & Support">
          <SubSection title="13.1 Availability">
            <p>The Provider targets 99.9% monthly uptime for the Platform, excluding scheduled maintenance windows. Uptime is measured at the Platform&rsquo;s API gateway. Specific commitments and service credits for downtime exceeding the SLA target are set forth in the Service Level Agreement.</p>
          </SubSection>
          <SubSection title="13.2 Scheduled Maintenance">
            <p>The Provider will provide at least 48 hours&rsquo; advance notice for scheduled maintenance that may affect availability. Where practicable, maintenance will be performed during off-peak hours (00:00&ndash;06:00 UTC).</p>
          </SubSection>
          <SubSection title="13.3 Support">
            <p>The Provider will provide technical support in accordance with the support tier specified in the Order Form. Standard support includes business-hours email and in-platform support. Premium and Enterprise tiers include 24/7 support with dedicated account management.</p>
          </SubSection>
        </Section>

        <Section title="14. Governing Law & Dispute Resolution">
          <SubSection title="14.1 Governing Law">
            <p>This Agreement shall be governed by and construed in accordance with the laws of England and Wales, without regard to conflict of law principles.</p>
          </SubSection>
          <SubSection title="14.2 Dispute Resolution">
            <ol className="list-decimal pl-6 space-y-1">
              <li><span className="font-semibold" style={{ color: "hsl(0 0% 75%)" }}>Escalation</span> — The parties shall first attempt to resolve the dispute through good-faith negotiation between senior executives within 30 days of written notice.</li>
              <li><span className="font-semibold" style={{ color: "hsl(0 0% 75%)" }}>Mediation</span> — If negotiation fails, the parties shall submit the dispute to mediation under the CEDR Model Mediation Procedure.</li>
              <li><span className="font-semibold" style={{ color: "hsl(0 0% 75%)" }}>Litigation</span> — If mediation fails within 60 days, either party may bring proceedings before the courts of England and Wales, which shall have exclusive jurisdiction.</li>
            </ol>
          </SubSection>
          <SubSection title="14.3 Injunctive Relief">
            <p>Nothing in this Section prevents either party from seeking injunctive or other equitable relief from any court of competent jurisdiction to protect its intellectual property or Confidential Information.</p>
          </SubSection>
        </Section>

        <Section title="15. General Provisions">
          <SubSection title="15.1 Force Majeure">
            <p>Neither party shall be liable for any delay or failure to perform (other than payment obligations) to the extent caused by events beyond its reasonable control, including natural disasters, pandemics, war, terrorism, government actions, power failures, internet disruptions, or third-party cloud infrastructure outages.</p>
          </SubSection>
          <SubSection title="15.2 Assignment">
            <p>Neither party may assign this Agreement without the prior written consent of the other party, except in connection with a merger, acquisition, or sale of all or substantially all assets, provided the assignee agrees to be bound by these terms.</p>
          </SubSection>
          <SubSection title="15.3 Entire Agreement">
            <p>This Agreement, together with the Order Form, DPA, SLA, Acceptable Use Policy, and Privacy Policy, constitutes the entire agreement between the parties and supersedes all prior agreements. No amendment shall be effective unless in writing and agreed by both parties.</p>
          </SubSection>
          <SubSection title="15.4 Severability">
            <p>If any provision is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.</p>
          </SubSection>
          <SubSection title="15.5 Waiver">
            <p>No failure or delay in exercising any right shall operate as a waiver, nor shall any single or partial exercise preclude further exercise of that or any other right.</p>
          </SubSection>
          <SubSection title="15.6 Notices">
            <p>All notices shall be in writing, delivered to the addresses specified in the Order Form via email, registered post, or internationally recognised courier. Notices are deemed received upon confirmed delivery.</p>
          </SubSection>
          <SubSection title="15.7 Third-Party Rights">
            <p>This Agreement does not confer any rights on any person or entity other than the parties. The Contracts (Rights of Third Parties) Act 1999 shall not apply.</p>
          </SubSection>
          <SubSection title="15.8 Export Compliance">
            <p>The Client shall comply with all applicable export control and sanctions laws. The Client shall not export, re-export, or transfer any data, software, or services received under this Agreement to any prohibited country, entity, or person.</p>
          </SubSection>
          <SubSection title="15.9 Anti-Bribery">
            <p>Each party shall comply with the Bribery Act 2010 and all applicable anti-corruption laws in connection with this Agreement.</p>
          </SubSection>
        </Section>

        <Section title="16. Contact Information">
          <p className="mb-4">For contractual inquiries or notices:</p>
          <div className="mb-4">
            <p className="font-semibold" style={{ color: "hsl(0 0% 85%)" }}>Alexandria Limited — Legal Department</p>
            <p>Email: <a href="mailto:legal@alexandrialabs.uk" className="underline underline-offset-4 transition-colors" style={{ color: "hsl(var(--terminal))" }}>legal@alexandrialabs.uk</a></p>
            <p>Web: <a href="https://alexandrialabs.uk/terms" className="underline underline-offset-4 transition-colors" style={{ color: "hsl(var(--terminal))" }}>https://alexandrialabs.uk/terms</a></p>
          </div>
        </Section>

        <div className="text-center pt-8 text-xs italic" style={{ color: "hsl(0 0% 30%)" }}>
          — End of Terms and Conditions —
        </div>
      </div>
      <Footer />
    </div>
  );
};

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-12">
    <div className="h-px mb-10" style={{ background: "hsl(0 0% 15%)" }} />
    <h2 className="text-display text-2xl md:text-3xl tracking-tight mb-5" style={{ color: "hsl(0 0% 88%)" }}>
      {title}
    </h2>
    <div className="text-sm leading-relaxed" style={{ color: "hsl(0 0% 55%)" }}>
      {children}
    </div>
  </div>
);

const SubSection = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-6">
    <h3 className="text-base font-semibold mb-2" style={{ color: "hsl(0 0% 70%)" }}>
      {title}
    </h3>
    {children}
  </div>
);

const DefRow = ({ term, def }: { term: string; def: string }) => (
  <tr style={{ borderBottom: "1px solid hsl(0 0% 15%)" }}>
    <td className="px-4 py-3 font-semibold" style={{ color: "hsl(0 0% 70%)" }}>{term}</td>
    <td className="px-4 py-3" style={{ color: "hsl(0 0% 55%)" }}>{def}</td>
  </tr>
);

export default Terms;
